.TH "LPMD-DATACENTER" "1" "0.5" "GNM" "LPMD User's Reference Manual"
.SH "NAME"
lpmd\-datacenter \- process molecular dynamics output data in a modular way 
.SH "SYNOPSIS"
.B lpmd\-datacenter
[\fI\-i plugin:opt1,opt2,...\fR] [\fI\-o plugin:opt1,opt2,...\fR]
.br 
.B lpmd\-datacenter
\-h
.SH "DESCRIPTION"
.PP 
\fBLPMD\fR, Las Palmeras Molecular Dynamics, is a modular molecular dynamics simulation package, 
based completely on plugins. 
The \fBlpmd\-datacenter\fR command reads from a data file and outputs to another, optionally converting its format.
.TP 
\fB\-i\fR, \fB\-\-input\fR
loads an input plugin with parameters \fBopt1\fR, \fBopt2\fR, etc.
.TP
\fB\-o\fR, \fB\-\-output\fR
loads an output plugin with parameters \fBopt1\fR, \fBopt2\fR, etc.
.TP 
\fB\-h\fR, \fB\-\-help\fR
displays help and version information, and exits
.SH "AUTHOR"
Grupo de Nanomateriales, 
.B http://www.gnm.cl/
.SH "REPORTING BUGS"
Report bugs to <lpmd@gnm.cl>.
.SH "COPYRIGHT"
Copyright \(co 2008 Free Software Foundation, Inc.
.br 
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
lpmd(1), lpmd\-analyzer(1), lpmd\-converter(1), lpmd\-visualizer(1).
.br 
.br 
The user manual for
.B lpmd
is included as a PDF file together with the source packages.
You can also look up 
.B http://www.gnm.cl/lpmd/
for more information
